- id: poetry-requirements-sync
  name: Poetry Requirements Sync
  description: pre-commit hook for removing pkg-resources from requirements.txt
  entry: sync-requirements
  language: python
  require_serial: true
  files: |
    (?x)(
      ^(.*/)?pyproject\.toml$|
      ^(.*/)?poetry\.lock$|
      ^(.+/)?requirements(-dev)?\.txt$
    )
